language: node_js

node_js:
   - 10
   - lts/*
allow_failures:
   - node
arch:
   - amd64
   - ppc64le   

addons:
   apt:
    update: true
    packages: 
       - build-essential 
       - npm 
       - wget 
